# Generated by Django 5.2.7 on 2025-11-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacer_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathingsession',
            name='exhale_hold_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breathingsession',
            name='synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
