# Generated by Django 5.2.7 on 2025-11-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacer_api', '0002_breathingsession_exhale_hold_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathplan',
            name='exhale_hold_ms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
