/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/breathing1` | `/breathing1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/breathing2` | `/breathing2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/forgotpassword`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/login`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/signup`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomToast`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/breathingGuide/breathing-tips`; params?: Router.UnknownInputParams; } | { pathname: `/breathingGuide/_Colors`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/breathing1` | `/breathing1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/breathing2` | `/breathing2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/authentication/forgotpassword`; params?: Router.UnknownOutputParams; } | { pathname: `/authentication/login`; params?: Router.UnknownOutputParams; } | { pathname: `/authentication/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CustomToast`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/breathingGuide/breathing-tips`; params?: Router.UnknownOutputParams; } | { pathname: `/breathingGuide/_Colors`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/about${`?${string}` | `#${string}` | ''}` | `/about${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/breathing1${`?${string}` | `#${string}` | ''}` | `/breathing1${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/breathing2${`?${string}` | `#${string}` | ''}` | `/breathing2${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/authentication/forgotpassword${`?${string}` | `#${string}` | ''}` | `/authentication/login${`?${string}` | `#${string}` | ''}` | `/authentication/signup${`?${string}` | `#${string}` | ''}` | `/components/CustomToast${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/breathingGuide/breathing-tips${`?${string}` | `#${string}` | ''}` | `/breathingGuide/_Colors${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/breathing1` | `/breathing1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/breathing2` | `/breathing2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/forgotpassword`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/login`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/signup`; params?: Router.UnknownInputParams; } | { pathname: `/components/CustomToast`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/breathingGuide/breathing-tips`; params?: Router.UnknownInputParams; } | { pathname: `/breathingGuide/_Colors`; params?: Router.UnknownInputParams; };
    }
  }
}
